# Generated by Django 6.1.1 on 2026-10-04 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('age', models.IntegerField()),
                ('course', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=150)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('admission_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
