# Generated by Django 6.1.1 on 2026-10-05 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=20, unique=True)),
                ('owner_name', models.CharField(max_length=100)),
                ('owner_email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('vehicle_type', models.CharField(choices=[('Car', 'Car'), ('Bike', 'Bike'), ('Truck', 'Truck'), ('Bus', 'Bus')], max_length=20)),
                ('brand', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=100)),
                ('manufacturing_year', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('registration_date', models.DateField()),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
