# Generated by Django 6.1.1 on 2026-10-05 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelviewset_based_APIs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('Truck', 'Truck'), ('Tempo', 'Tempo'), ('Bus', 'Bus'), ('Van', 'Van'), ('SUV', 'SUV')], max_length=20),
        ),
    ]
